# name: Branch Delete Action

# on:
#   delete:
#     branches: 
#       - '**'

# jobs:
#   branch-deletion-message:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Fetch Default Branch Name
#         id: fetch-default-branch
#         run: |
#           DEFAULT_BRANCH=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
#           https://api.github.com/repos/${{ github.repository }} | jq -r '.default_branch')
#           echo "::set-output name=default_branch::$DEFAULT_BRANCH"
#           echo "Fetched default branch is $DEFAULT_BRANCH"
#         shell: bash

#       - name: Output Default Branch
#         run: echo "The default branch of this repository is ${{ steps.fetch-default-branch.outputs.default_branch }}."

#       - name: Output This Branch Name
#         run: echo "This branch is ${{ github.event.ref }}."        

#       - name: Print Deletion Message
#         if: ${{ github.event.ref != 'main' && github.event.ref != 'master' && github.event.ref != steps.fetch-default-branch.outputs.default_branch }}
#         run: echo "Hello World, I am deleting ${{ github.event.ref }}"
