name: Branch Delete Action

on:
  delete:
    branches: 
      - '**'

permissions: read-all

jobs:
  call-shared-workflow:
    #uses: snodnipper/random/.github/workflows/shared.yml@main
    uses: ./.github/workflows/shared.yml
    with:
      branch-name: ${{ github.event.ref }}
      #github-token: ${{ secrets.GITHUB_TOKEN }} 
