name: Branch Delete Action

on:
  delete:
    branches: 
      - '**'

jobs:
  call-shared-workflow:
    uses: snodnipper/random/.github/workflows/shared.yml@main
    with:
      branch-name: ${{ github.event.ref }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
