name: Branch Delete Action

on:
  delete:
    branches: 
      - '**'

jobs:
  call-shared-workflow:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Invoke Shared Workflow
        uses: .github/workflows/shared.yml
        with:
          branch-name: ${{ github.event.ref }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
