name: Branch Delete Action

on:
  delete:
    branches: 
      - '**'

jobs:
  call-echo-branch-name-workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Call Echo Branch Name Workflow
        uses: ./.github/workflows/shared.yml
        with:
          branch-name: ${{ github.event.ref }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
