name: Reusable Echo Workflow

on:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string
        description: 'The name of the branch being processed.'

jobs:
  branch-check-and-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Default Branch Name
        id: fetch-default-branch
        run: |
          DEFAULT_BRANCH=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }} | jq -r '.default_branch')
          echo "Fetched default branch is $DEFAULT_BRANCH"
        shell: bash

      - name: Check and Echo Branch Name
        if: ${{ inputs.branch-name != 'main' && inputs.branch-name != 'master' && inputs.branch-name != env.DEFAULT_BRANCH }}
        run: echo "Hello World, I am deleting ${{ inputs.branch-name }}"
